export enum Weather {
    WEATHER_WIDGETS = 'WEATHER WIDGETS',
    ENTER_CITY_NAME = ' Enter a city name to get started'
}

export enum ActionText {
    ADD_CITY = 'ADD_CITY',
    REMOVE_CITY = 'REMOVE_CITY',
    UPDATE_CITY = 'UPDATE_CITY',
    // GET_WEATHER_CARD_DETAILS_BY_ID_REQUEST = 'GET_WEATHER_CARD_DETAILS_BY_ID_REQUEST',
    // GET_WEATHER_CARD_DETAILS_BY_ID_SUCCESS = 'GET_WEATHER_CARD_DETAILS_BY_ID_SUCCESS',
    // RESET_USER_CARD_DETAILS = 'RESET_USER_CARD_DETAILS',


}